name: biztoso
description: "Biztoso Flutter Application - Social Media Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons Packages
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  eva_icons_flutter: ^3.1.0
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1

  # Google Fonts Package
  google_fonts: ^6.2.1

  # State Management Packages
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Dependency Injection Package
  get_it: ^8.0.3

  # Navigation Package
  go_router: ^16.0.0

  #
  intl: ^0.20.2

  # Network Library
  dio: ^5.8.0+1

  # Share app or link with third party app
  share_plus: ^11.0.0

  # Video Player for Post and Shorts
  video_player: ^2.10.0

  path_provider: ^2.1.5
  visibility_detector: ^0.4.0+2
  image_picker: ^1.1.2
  dotted_border: ^3.1.0
  connectivity_plus: ^6.1.4
  flutter_secure_storage: ^9.2.4
  device_info_plus: ^11.5.0
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  bloc_concurrency: ^0.3.0
  rxdart: ^0.28.0
  url_launcher: ^6.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
